FROM node

RUN npm install -g pm2
RUN mkdir /home/api

WORKDIR /home/api

EXPOSE 3000


#RUN npm --version

CMD npm install && npm run build && pm2 start ./dist/index.js --name "miro"
#npm run dev
#[ "nodemon", "./dist/index.js" ]
#CMD [ "npm", "run dev" ]